/**
 * @file main.cpp
 * @brief SEIRD model using the new_state_update_transition factory
 *
 * Demonstrates how to build a Susceptible-Exposed-Infected-Recovered-Deceased
 * (SEIRD) model where the Exposed and Infected state update functions are
 * generated by the `new_state_update_transition` factory instead of being
 * hand-written lambdas.
 *
 * Flow:
 *   S --virus--> E --rate--> I --rate--> R
 *                                \--rate--> D
 */
#include "../../include/epiworld/epiworld.hpp"

using namespace epiworld;

int main()
{

    // State codes (order of add_state calls)
    constexpr epiworld_fast_uint S = 0u;
    constexpr epiworld_fast_uint E = 1u;
    constexpr epiworld_fast_uint I = 2u;
    constexpr epiworld_fast_uint R = 3u;
    constexpr epiworld_fast_uint D = 4u;

    // Build transition update functions using the factory
    auto update_exposed = new_state_update_transition<int>(
        {"E->I transition rate"},
        {I}
    );

    auto update_infected = new_state_update_transition<int>(
        {"I->R transition rate", "I->D transition rate"},
        {R, D}
    );

    // Assemble the model
    Model<int> model;

    model.add_state("Susceptible", default_update_susceptible<int>);
    model.add_state("Exposed",     update_exposed);
    model.add_state("Infected",    update_infected);
    model.add_state("Recovered");
    model.add_state("Deceased");

    // Model parameters
    model.add_param(0.3, "Transmission rate");
    model.add_param(1.0 / 7.0, "E->I transition rate");
    model.add_param(0.5, "I->R transition rate");
    model.add_param(0.01, "I->D transition rate");

    // Virus
    Virus<int> virus("A flu", 0.01, true);
    virus.set_state(E, R, D);
    virus.set_prob_infecting("Transmission rate");
    model.add_virus(virus);

    // Population
    model.agents_smallworld(10000, 20, false, 0.01);

    // Run and display
    model.run(100, 123);
    model.print();

    return 0;

}
