var searchData=
[
  ['make_5fsample_5fvirus_5fneighbors_50',['make_sample_virus_neighbors',['../namespacesampler.html#a4671a91fd9b8fececf5364dd5d5b4ac2',1,'sampler']]],
  ['make_5fupdate_5fsusceptible_51',['make_update_susceptible',['../namespacesampler.html#a001ac6eee849afcdd3e6904500c77fa4',1,'sampler']]],
  ['mit_20license_52',['MIT License',['../md__l_i_c_e_n_s_e.html',1,'']]],
  ['mixing_20probabilities_20in_20connected_20model_53',['Mixing probabilities in connected model',['../md_paper_mixing.html',1,'']]],
  ['model_54',['Model',['../class_model.html',1,'']]],
  ['model1_55',['model1',['../md_model1.html',1,'']]],
  ['model_3c_20epi_5fdefault_5ftseq_20_3e_56',['Model&lt; EPI_DEFAULT_TSEQ &gt;',['../class_model.html',1,'']]],
  ['modeldiagram_57',['ModelDiagram',['../class_model_diagram.html',1,'']]],
  ['modeldiffnet_58',['ModelDiffNet',['../class_model_diff_net.html',1,'']]],
  ['modelmeaslesquarantine_59',['ModelMeaslesQuarantine',['../class_model_measles_quarantine.html',1,'ModelMeaslesQuarantine&lt; TSeq &gt;'],['../class_model_measles_quarantine.html#ae99078b141176000eb305ffb6920842f',1,'ModelMeaslesQuarantine::ModelMeaslesQuarantine()']]],
  ['modelseir_60',['ModelSEIR',['../class_model_s_e_i_r.html',1,'']]],
  ['modelseirconn_61',['ModelSEIRCONN',['../class_model_s_e_i_r_c_o_n_n.html',1,'ModelSEIRCONN&lt; TSeq &gt;'],['../class_model_s_e_i_r_c_o_n_n.html#a995ce6a24b286635bd594a793e2c8f77',1,'ModelSEIRCONN::ModelSEIRCONN()']]],
  ['modelseird_62',['ModelSEIRD',['../class_model_s_e_i_r_d.html#a6cc32d0aeb08a666ef59d818d02a52b8',1,'ModelSEIRD::ModelSEIRD()'],['../class_model_s_e_i_r_d.html',1,'ModelSEIRD&lt; TSeq &gt;'],['../class_model_s_e_i_r_d.html#a31dbc41fb62f30a072274ddddda497c7',1,'ModelSEIRD::ModelSEIRD()']]],
  ['modelseirdconn_63',['ModelSEIRDCONN',['../class_model_s_e_i_r_d_c_o_n_n.html',1,'ModelSEIRDCONN&lt; TSeq &gt;'],['../class_model_s_e_i_r_d_c_o_n_n.html#a5fabd2a0fc8eb5d618ef0bff329f04e4',1,'ModelSEIRDCONN::ModelSEIRDCONN()']]],
  ['modelseirmixing_64',['ModelSEIRMixing',['../class_model_s_e_i_r_mixing.html',1,'ModelSEIRMixing&lt; TSeq &gt;'],['../class_model_s_e_i_r_mixing.html#abf1da94d6b16f8ae64d7302e0a41e41b',1,'ModelSEIRMixing::ModelSEIRMixing(ModelSEIRMixing&lt; TSeq &gt; &amp;model, const std::string &amp;vname, epiworld_fast_uint n, epiworld_double prevalence, epiworld_double contact_rate, epiworld_double transmission_rate, epiworld_double avg_incubation_days, epiworld_double recovery_rate, std::vector&lt; double &gt; contact_matrix)'],['../class_model_s_e_i_r_mixing.html#ab02c9e3f95e1cd213f16d6761709debc',1,'ModelSEIRMixing::ModelSEIRMixing(const std::string &amp;vname, epiworld_fast_uint n, epiworld_double prevalence, epiworld_double contact_rate, epiworld_double transmission_rate, epiworld_double avg_incubation_days, epiworld_double recovery_rate, std::vector&lt; double &gt; contact_matrix)']]],
  ['modelsir_65',['ModelSIR',['../class_model_s_i_r.html',1,'']]],
  ['modelsirconn_66',['ModelSIRCONN',['../class_model_s_i_r_c_o_n_n.html',1,'ModelSIRCONN&lt; TSeq &gt;'],['../class_model_s_i_r_c_o_n_n.html#a1521e30911e218a5d76e77617e6f6a20',1,'ModelSIRCONN::ModelSIRCONN()']]],
  ['modelsird_67',['ModelSIRD',['../class_model_s_i_r_d.html#a8552373be0c7761f45d7afe6604a125b',1,'ModelSIRD::ModelSIRD()'],['../class_model_s_i_r_d.html',1,'ModelSIRD&lt; TSeq &gt;']]],
  ['modelsirdconn_68',['ModelSIRDCONN',['../class_model_s_i_r_d_c_o_n_n.html#a3293df75e9449dadceaa20768e3e492d',1,'ModelSIRDCONN::ModelSIRDCONN()'],['../class_model_s_i_r_d_c_o_n_n.html',1,'ModelSIRDCONN&lt; TSeq &gt;']]],
  ['modelsirlogit_69',['ModelSIRLogit',['../class_model_s_i_r_logit.html#a6d177acf2853f118d3170ce9c7e368e8',1,'ModelSIRLogit::ModelSIRLogit()'],['../class_model_s_i_r_logit.html',1,'ModelSIRLogit&lt; TSeq &gt;']]],
  ['modelsirmixing_70',['ModelSIRMixing',['../class_model_s_i_r_mixing.html#aa4a1d6bc3cb551f2109d392e762baef3',1,'ModelSIRMixing::ModelSIRMixing(ModelSIRMixing&lt; TSeq &gt; &amp;model, const std::string &amp;vname, epiworld_fast_uint n, epiworld_double prevalence, epiworld_double contact_rate, epiworld_double transmission_rate, epiworld_double recovery_rate, std::vector&lt; double &gt; contact_matrix)'],['../class_model_s_i_r_mixing.html#ac5761109351b367a9c903807f6503997',1,'ModelSIRMixing::ModelSIRMixing(const std::string &amp;vname, epiworld_fast_uint n, epiworld_double prevalence, epiworld_double contact_rate, epiworld_double transmission_rate, epiworld_double recovery_rate, std::vector&lt; double &gt; contact_matrix)'],['../class_model_s_i_r_mixing.html',1,'ModelSIRMixing&lt; TSeq &gt;']]],
  ['modelsis_71',['ModelSIS',['../class_model_s_i_s.html',1,'']]],
  ['modelsisd_72',['ModelSISD',['../class_model_s_i_s_d.html',1,'']]],
  ['modelsurv_73',['ModelSURV',['../class_model_s_u_r_v.html',1,'']]]
];
