#define CATCH_CONFIG_MAIN
#include "../include/catch2/catch.hpp"

#define epiworld_double double
#include "../include/epiworld/epiworld.hpp"
#include "tests.hpp"


// #include "00-cloning-model.cpp"
// #include "00-lfmcmc.cpp"
// #include "01-model-methods.cpp"
// #include "01-sir.cpp"
// #include "01b-sir.cpp"
// #include "01c-sir.cpp"
// #include "01-sirconnected.cpp"
// #include "02-reproducible-sir.cpp"
// #include "02-reproducible-sirconn.cpp"
// #include "04-initial-dist.cpp"
// #include "05-mixing.cpp"
// #include "05b-mixing.cpp"
// #include "05c-mixing.cpp"
// #include "06-mixing.cpp"
// #include "07-entitifuns.cpp"
// #include "09-distribute-tools-and-viruses.cpp"
// #include "10-generation-interval.cpp"
// #include "11-random-numbers.cpp"
// #include "12-diagrams.cpp"
// #include "13-rt.cpp"
// #include "14a-measles.cpp"
// #include "14b-measles.cpp"
// #include "14c-measles.cpp"
// #include "15-edgelist-after-run-multiple.cpp"
// #include "16-multiple-events.cpp"
#include "17a-mixing-quarantine.cpp"
#include "17b-mixing-quarantine.cpp"
#include "17c-mixing-quarantine.cpp"
