#define CATCH_CONFIG_MAIN
#include "../include/catch2/catch.hpp"

#define epiworld_double double
#include "../include/epiworld/epiworld.hpp"
#include "tests.hpp"


#include "00-cloning-model.cpp"
#include "00-lfmcmc.cpp"
#include "01-model-methods.cpp"
#include "01-sir.cpp"
#include "01b-sir.cpp"
#include "01c-sir.cpp"
#include "01-sirconnected.cpp"
#include "02-reproducible-sir.cpp"
#include "02-reproducible-sirconn.cpp"
#include "04-initial-dist.cpp"
#include "05-mixing.cpp"
#include "05b-mixing.cpp"
#include "05c-mixing.cpp"
#include "06-mixing.cpp"
#include "07-entitifuns.cpp"
#include "09-distribute-tools-and-viruses.cpp"
#include "10-generation-interval.cpp"
#include "11-random-numbers.cpp"
#include "12-diagrams.cpp"
#include "13-rt.cpp"
#include "14a-measles.cpp"
#include "14b-measles.cpp"
#include "14c-measles.cpp"
#include "14d-measles.cpp"
#include "15-edgelist-after-run-multiple.cpp"
#include "16-multiple-events.cpp"
#include "17a-mixing-quarantine.cpp"
#include "17b-mixing-quarantine.cpp"
#include "17c-mixing-quarantine.cpp"

// These two tests are excluded b/c they used a version
// of the model that featured parameters that were later
// removed (entity_can_quarantine).
// Will be re-added with updated versions later.
// #include "17d-mixing-quarantine.cpp"
// #include "17e-mixing-quarantine.cpp"
#include "19a-measles-mixing.cpp"
#include "19b-measles-mixing.cpp"
#include "19c-measles-mixing.cpp"
#include "20a-measles-mixing-risk-quarantine-basic.cpp"
#include "20b-measles-mixing-risk-quarantine-transitions.cpp"
#include "20c-measles-mixing-risk-quarantine-durations.cpp"
#include "20d-measles-mixing-risk-quarantine-process.cpp"
#include "21a-rewire-degseq.cpp"
#include "21b-rewire-degseq.cpp"
#include "22a-globalevents.cpp"
#include "22b-globalevents.cpp"
#include "23a-distribute-tool-virus-to-entities.cpp"
#include "23b-distribute-tool-virus-to-entities.cpp"
#include "24a-virus-hist-single-run.cpp"
#include "24b-csv-output-format.cpp"
#include "24c-virus-hist-multiple-sims.cpp"
#include "25a-hospitalizationstracker.cpp"

