flowchart TB

    %% Disease progression states
    subgraph Main[Disease Progression]
        direction TB
        S[Susceptible]
        E[Latent]
        P[Prodromal]
        Ra[Rash]
        Re[Recovered]
        H[Hospitalized]
    end

    S --> E
    E --> P
    P --> Ra
    Ra --> Re
    
    Ra --> H
    H --> Re

    %% Quarantine states
    Qe[Quarantined<br>Latent]
    Qs[Quarantined<br>Susceptible]
    Qp[Quarantined<br>Prodromal]
    I[Isolated]
    Ir[Isolated<br>Recovered]

    %% Isolation process
    Ra <==> I
    Ra --> Ir
    Ra --> H

    I --> Re
    I --> H

    I --> Ir
    Ir --> Re

    %% Quarantine process
    S <==> Qs
    E <==> Qe

    Qe --> Qp
    Qp --> I
    Qp --> Ra

    P <==> Qp
