name: perl-setup
description: Cache cpanm and install Perl dependencies
inputs:
  llvm:
    description: 'LLVM version to use'
    required: true
runs:
  using: composite
  steps:
    - name: Cache cpanm
      uses: actions/cache@v4
      with:
        path: ~/.cpanm
        key: "${{ runner.os }}-llvm${{ inputs.llvm }}-cpanm-${{ hashFiles('**/cpanfile') }}"

    - name: Install Perl modules
      shell: bash
      run: |
        if [ "$(uname)" = "Darwin" ]; then
          export PKG_CONFIG_PATH="$(brew --prefix libxml2)/lib/pkgconfig:$PKG_CONFIG_PATH"
        fi
        cpanm --notest --installdeps .
