# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname new_model
#' @export
add_tool_immune <- function(model, baselineseq, preval) {
    invisible(.Call(`_epiworld_add_tool_immune`, model, baselineseq, preval))
}

#' @rdname new_model
#' @export
add_tool_mask <- function(model, baselineseq, preval) {
    invisible(.Call(`_epiworld_add_tool_mask`, model, baselineseq, preval))
}

#' @rdname new_model
#' @export
add_tool_vaccine <- function(model, baselineseq, preval) {
    invisible(.Call(`_epiworld_add_tool_vaccine`, model, baselineseq, preval))
}

#' @export
#' @rdname new_model
add_virus_covid19 <- function(model, baselineseq, preval) {
    invisible(.Call(`_epiworld_add_virus_covid19`, model, baselineseq, preval))
}

#' Create a new model
#' @export
new_model <- function() {
    .Call(`_epiworld_new_model`)
}

#' @export
#' @rdname new_model
run_model <- function(model, nsteps, seed) {
    invisible(.Call(`_epiworld_run_model`, model, nsteps, seed))
}

