# Defines a program.

include share/mk/epw.compile.mk

# Pick our linker based on what languages this program is made of.
ifneq ($(strip $(filter %.cpp,$($(NAME)_SOURCES))),)
	$(NAME)_LINKER := $(CXX)
else
	$(NAME)_LINKER := $(CC)
endif

include share/mk/epw.artifact.mk
	
$($(NAME)_BUILD_DIR)/$(NAME): override NAME := $(NAME)
$($(NAME)_BUILD_DIR)/$(NAME): $($(NAME)_OBJS)
	$(SAY) "LD" $@
	$(V)mkdir -p $(dir $@)
	$(V)$($(NAME)_LINKER) -o $@ $(LDFLAGS) $($(NAME)_LDFLAGS) $($(NAME)_OBJS)
	
ALL_PROGRAMS                            += $($(NAME)_BUILD_DIR)/$(NAME)
$($(NAME)_BUILD_DIR)/$(NAME)_DISPATCHES := $(addprefix $($(NAME)_SOURCE_DIR)/,$($(NAME)_SOURCES))
	
#.PHONY: $(NAME)
#$(NAME): override NAME := $(NAME)
#$(NAME): $($(NAME)_BUILD_DIR)/$(NAME)
#	$(SAY) "RUN" $@
#	$(V)$($(NAME)_BUILD_DIR)/$(NAME)
#	
#TARGET_LIST += $(NAME)
	
# Include all the dependency files generated by the compiler.
$(eval -include $($(NAME)_DEPFILES))

