name: Clang Format Check

on:
    pull_request:
        paths:
            - "**.cpp"
            - "**.cc"
            - "**.cxx"
            - "**.h"
            - "**.hpp"

jobs:
    clang-format:
        name: Check C++ Formatting
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install clang-format
              run: sudo apt-get install -y clang-format

            - name: Run clang-format
              run: |
                  FILES=$(find . -type f \( -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" -o -name "*.h" -o -name "*.hpp" \) -print0)
                  echo "$FILES" | xargs -0 clang-format -style=file -i

            - name: Check for formatting changes
              run: |
                  if ! git diff --exit-code; then
                    echo "❌ Formatting issues found. Please run clang-format.";
                    git --no-pager diff
                    exit 1
                  else
                    echo "✅ No formatting issues found."
                  fi
